root = "."
tmp_dir = "tmp"
[build]
  bin = "tmp/main"
  cmd = "go build -o tmp/main ."
  clean_cmd = "rm -rf ./tmp/main"
  include_ext = ["go", "html", "tmpl"]
  exclude_dir = ["vendor", "tmp", "frontend", "data"]
  delay = 1000
  full_bin = "tmp/main 2>&1 | tee /dev/stderr"
[log]
  level = "debug"

