[project]
name = "admin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "django>=5.2.5",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.1.1",
    "supabase>=2.18.1",
    "whitenoise>=6.8.2",
]
