# Generated by Django 5.2.7 on 2025-10-19 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('filename', models.CharField(max_length=200, unique=True)),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('photo_type', models.CharField(choices=[('product', 'Product Photo'), ('blog', 'Blog Photo')], default='product', max_length=20)),
            ],
            options={
                'ordering': ['photo_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text/Paragraph'), ('photo', 'Photo'), ('youtube', 'YouTube Video')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('text_content', models.TextField(blank=True, help_text='For text blocks', null=True)),
                ('youtube_url', models.CharField(blank=True, help_text="YouTube video ID (e.g., 'rmojioqOlzk')", max_length=200, null=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='farmsville.blogpost')),
                ('photo', models.ForeignKey(blank=True, help_text='For photo blocks', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmsville.photo')),
            ],
            options={
                'ordering': ['blog_post', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farmsville.event')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='farmsville.photo')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='farmsville.productname')),
            ],
            options={
                'ordering': ['event', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductClaimed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('user_name', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='farmsville.product')),
            ],
            options={
                'verbose_name_plural': 'Products Claimed',
                'ordering': ['-datetime'],
            },
        ),
    ]
