# Generated by Django 5.2.7 on 2025-10-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsville', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['photo_type', 'name']},
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('product', 'Product Photo'), ('blog', 'Blog Photo')], default='product', max_length=20),
        ),
    ]
