# Generated by Django 5.2.7 on 2025-10-14 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsville', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, unique=True)),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['caption', 'filename'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='farmsville.photo'),
        ),
    ]
