# Generated by Django 5.2.7 on 2026-01-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsville', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productclaimed',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
