# Generated by Django 5.2.7 on 2025-10-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmsville', '0002_alter_photo_options_photo_photo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='youtube_url',
            field=models.CharField(blank=True, help_text="YouTube video ID (e.g., 'rmojioqOlzk')", max_length=200, null=True),
        ),
    ]
